"use client";

import { FormEvent, useEffect, useState } from "react";
import AppLayout from "@/components/app-layout";
import { createClient } from "@/lib/supabase";

type Routine = { id: string; name: string; goal: string | null; active: boolean; study_blocks?: Block[] };
type Block = { id: string; subject: string; topic: string | null; theory_minutes: number; question_minutes: number; break_minutes: number; position: number };

export default function RotinasPage() {
  const [routines,setRoutines]=useState<Routine[]>([]); const [name,setName]=useState(""); const [goal,setGoal]=useState(""); const [open,setOpen]=useState(false); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
  async function load(){ const {data,error}=await createClient().from("routines").select("*,study_blocks(*)").order("created_at",{ascending:false}); if(error)setMessage(error.message); else setRoutines((data??[]) as Routine[]); }
  useEffect(()=>{load();},[]);
  async function create(event:FormEvent){event.preventDefault();setBusy(true);const supabase=createClient();const {data:{user}}=await supabase.auth.getUser();const {error}=await supabase.from("routines").insert({user_id:user?.id,name,goal});setBusy(false);if(error)setMessage(error.message);else{setName("");setGoal("");setOpen(false);load();}}
  async function addBlock(routineId:string){const subject=window.prompt("Matéria do bloco:");if(!subject)return;const topic=window.prompt("Tópico (opcional):")??"";const minutes=Number(window.prompt("Minutos de teoria:","30")??30);const supabase=createClient();const {data:{user}}=await supabase.auth.getUser();const position=(routines.find(r=>r.id===routineId)?.study_blocks?.length??0)+1;const {error}=await supabase.from("study_blocks").insert({user_id:user?.id,routine_id:routineId,subject,topic,theory_minutes:minutes,question_minutes:15,break_minutes:5,position});if(error)setMessage(error.message);else load();}
  async function remove(id:string){if(!confirm("Excluir esta rotina?"))return;const {error}=await createClient().from("routines").delete().eq("id",id);if(error)setMessage(error.message);else load();}
  return <AppLayout><div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold text-blue-700">PLANEJAMENTO</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Rotinas e cronogramas</h1><p className="mt-2 text-slate-500">Organize seus blocos e avance em sequência.</p></div><button onClick={()=>setOpen(!open)} className="rounded-xl bg-blue-600 px-5 py-3 text-sm font-semibold text-white">+ Nova rotina</button></div>{open&&<form onSubmit={create} className="mb-6 grid gap-3 rounded-2xl border border-blue-100 bg-blue-50 p-5 md:grid-cols-[1fr_1fr_auto]"><input value={name} onChange={e=>setName(e.target.value)} required placeholder="Nome da rotina" className="rounded-xl border border-slate-200 bg-white px-4 py-3 outline-none focus:ring-2 focus:ring-blue-500"/><input value={goal} onChange={e=>setGoal(e.target.value)} placeholder="Objetivo (opcional)" className="rounded-xl border border-slate-200 bg-white px-4 py-3 outline-none focus:ring-2 focus:ring-blue-500"/><button disabled={busy} className="rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white">{busy?"Salvando...":"Criar"}</button></form>}{message&&<p className="mb-5 rounded-xl bg-red-50 p-3 text-sm text-red-700">{message}</p>}<div className="grid gap-5 lg:grid-cols-2">{routines.map(r=><article key={r.id} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex justify-between gap-4"><div><h2 className="text-lg font-bold">{r.name}</h2><p className="mt-1 text-sm text-slate-500">{r.goal||"Sem objetivo definido"}</p></div><button onClick={()=>remove(r.id)} className="text-sm font-semibold text-slate-400 hover:text-red-600">Excluir</button></div><div className="mt-5 space-y-2">{(r.study_blocks??[]).sort((a,b)=>a.position-b.position).map((b,i)=><div key={b.id} className="flex items-center justify-between rounded-xl bg-slate-50 px-4 py-3"><div><span className="mr-2 text-xs font-bold text-blue-600">{i+1}</span><span className="font-semibold">{b.subject}</span>{b.topic&&<span className="ml-2 text-sm text-slate-500">· {b.topic}</span>}</div><span className="text-xs text-slate-500">{b.theory_minutes}min teoria · {b.question_minutes}min questões</span></div>)}{!(r.study_blocks??[]).length&&<p className="rounded-xl border border-dashed border-slate-200 p-4 text-sm text-slate-500">Adicione o primeiro bloco de estudo.</p>}</div><button onClick={()=>addBlock(r.id)} className="mt-5 text-sm font-semibold text-blue-700">+ Adicionar bloco</button></article>)}</div>{!routines.length&&!message&&<Empty text="Crie sua primeira rotina para montar seu cronograma."/>}</AppLayout>;
}
function Empty({text}:{text:string}){return <div className="grid place-items-center rounded-2xl border border-dashed border-slate-300 bg-white p-12 text-center text-slate-500">{text}</div>}
