"use client";

import { useEffect, useMemo, useState } from "react";
import AppLayout from "@/components/app-layout";
import { createClient } from "@/lib/supabase";

type Session = { id: string; subject: string; started_at: string; duration_minutes: number; status: string };
type View = "month" | "week" | "list";
type Holiday = { name: string; date: Date };
const weekdays = ["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sáb"];

function addDays(date: Date, amount: number) { const next = new Date(date); next.setDate(next.getDate() + amount); return next; }
function equalDate(a: Date, b: Date) { return a.getFullYear() === b.getFullYear() && a.getMonth() === b.getMonth() && a.getDate() === b.getDate(); }
function easter(year: number) { const a=year%19,b=Math.floor(year/100),c=year%100,d=Math.floor(b/4),e=b%4,f=Math.floor((b+8)/25),g=Math.floor((b-f+1)/3),h=(19*a+b-d-g+15)%30,i=Math.floor(c/4),k=c%4,l=(32+2*e+2*i-h-k)%7,m=Math.floor((a+11*h+22*l)/451),n=h+l-7*m+114; return new Date(year,Math.floor(n/31)-1,n%31+1); }
function holidays(year: number): Holiday[] { const e=easter(year); const fixed:[[number,number,string],...Array<[number,number,string]>]=[[0,1,"Confraternização Universal"],[3,21,"Tiradentes"],[4,1,"Dia do Trabalho"],[8,7,"Independência do Brasil"],[9,12,"Nossa Senhora Aparecida"],[10,2,"Finados"],[10,15,"Proclamação da República"],[10,20,"Dia da Consciência Negra"],[11,25,"Natal"]]; return fixed.map(([m,d,name])=>({date:new Date(year,m,d),name})).concat([{date:addDays(e,-47),name:"Carnaval"},{date:addDays(e,-46),name:"Carnaval"},{date:addDays(e,-2),name:"Paixão de Cristo"},{date:e,name:"Páscoa"},{date:addDays(e,60),name:"Corpus Christi"}]); }

export default function CalendarPage() {
  const [sessions, setSessions] = useState<Session[]>([]); const [month, setMonth] = useState(new Date()); const [view, setView] = useState<View>("month"); const [query, setQuery] = useState(""); const [completed, setCompleted] = useState(true); const [selected, setSelected] = useState(new Date()); const [message, setMessage] = useState("");
  useEffect(()=>{createClient().from("study_sessions").select("*").order("started_at",{ascending:false}).then(({data,error})=>error?setMessage(error.message):setSessions((data??[])as Session[]))},[]);
  const year=month.getFullYear(), number=month.getMonth(), start=new Date(year,number,1).getDay(), totalDays=new Date(year,number+1,0).getDate();
  const cells=Array.from({length:Math.ceil((start+totalDays)/7)*7},(_,i)=>i>=start&&i<start+totalDays?i-start+1:null);
  const visible=useMemo(()=>sessions.filter(s=>s.subject.toLowerCase().includes(query.toLowerCase())&&(!completed||s.status==="completed")),[sessions,query,completed]);
  const allHolidays=useMemo(()=>holidays(year),[year]); const sessionsOn=(date:Date)=>visible.filter(s=>equalDate(new Date(s.started_at),date)); const selectedSessions=sessionsOn(selected); const selectedHoliday=allHolidays.find(h=>equalDate(h.date,selected)); const total=visible.filter(s=>s.status==="completed").reduce((sum,s)=>sum+s.duration_minutes,0);
  function shift(amount:number){setMonth(new Date(year,number+amount,1));}
  return <AppLayout><div className="mb-7 flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="text-sm font-semibold text-blue-700">SEU HISTÓRICO</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Calendário de estudos</h1><p className="mt-2 text-slate-500">Clique em uma data para ver o que aconteceu naquele dia.</p></div><div className="rounded-xl border border-slate-200 bg-white p-1">{(["month","week","list"]as View[]).map(v=><button key={v} onClick={()=>setView(v)} className={`rounded-lg px-3 py-2 text-sm font-bold ${view===v?"bg-blue-600 text-white":"text-slate-500 hover:bg-slate-100"}`}>{v==="month"?"Mês":v==="week"?"Semana":"Lista"}</button>)}</div></div>
  <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:p-6"><div className="flex flex-col gap-4 border-b border-slate-100 pb-5 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-center gap-2"><button onClick={()=>shift(-1)} className="grid size-9 place-items-center rounded-lg border border-slate-200 text-xl">‹</button><button onClick={()=>{const now=new Date();setMonth(now);setSelected(now)}} className="rounded-lg border border-slate-200 px-3 py-2 text-sm font-bold">Hoje</button><button onClick={()=>shift(1)} className="grid size-9 place-items-center rounded-lg border border-slate-200 text-xl">›</button><h2 className="ml-2 text-lg font-bold capitalize">{month.toLocaleDateString("pt-BR",{month:"long",year:"numeric"})}</h2></div><div className="flex gap-2"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar matéria..." className="h-10 min-w-0 flex-1 rounded-lg border border-slate-200 px-3 text-sm outline-none focus:ring-2 focus:ring-blue-100 sm:w-52"/><button onClick={()=>setCompleted(v=>!v)} className={`rounded-lg border px-3 text-sm font-bold ${completed?"border-blue-200 bg-blue-50 text-blue-700":"border-slate-200"}`}>{completed?"Concluídas":"Todas"}</button></div></div>
  {view==="month"&&<div className="mt-5 grid gap-5 xl:grid-cols-[1fr_280px]"><div><div className="grid grid-cols-7 border-b border-slate-100">{weekdays.map(d=><span key={d} className="p-2 text-center text-xs font-bold uppercase text-slate-400">{d}</span>)}</div><div className="grid grid-cols-7">{cells.map((day,index)=>{if(!day)return <div key={index} className="min-h-24 border-b border-r border-slate-100 bg-slate-50/50"/>;const date=new Date(year,number,day),items=sessionsOn(date),holiday=allHolidays.find(h=>equalDate(h.date,date)),today=equalDate(date,new Date()),isSelected=equalDate(date,selected);return <button key={index} onClick={()=>setSelected(date)} className={`min-h-24 border-b border-r border-slate-100 p-2 text-left transition hover:bg-blue-50 ${isSelected?"bg-blue-50 ring-2 ring-inset ring-blue-500":""}`}><span className={`grid size-7 place-items-center rounded-full text-sm ${today?"bg-blue-600 font-bold text-white":"text-slate-700"}`}>{day}</span>{holiday&&<p className="mt-1 truncate text-[10px] font-bold text-orange-700">● {holiday.name}</p>}{items.slice(0,2).map(s=><p key={s.id} className="mt-1 truncate rounded bg-blue-100 px-1 py-0.5 text-[10px] font-bold text-blue-800">{s.subject} · {s.duration_minutes}m</p>)}</button>})}</div></div><DayPanel date={selected} sessions={selectedSessions} holiday={selectedHoliday}/></div>}
  {view==="week"&&<Week sessions={visible} selected={selected} onSelect={setSelected}/>} {view==="list"&&<List sessions={visible} onSelect={(date)=>{setSelected(date);setView("month");setMonth(date)}}/>}</section>
  <div className="mt-6 grid gap-4 sm:grid-cols-3"><Stat label="Tempo estudado" value={`${Math.floor(total/60)}h ${total%60}m`}/><Stat label="Sessões" value={String(visible.length)}/><Stat label="Dias com foco" value={String(new Set(visible.map(s=>new Date(s.started_at).toDateString())).size)}/></div>{message&&<p className="mt-4 text-sm text-red-600">{message}</p>}</AppLayout>;
}
function DayPanel({date,sessions,holiday}:{date:Date;sessions:Session[];holiday?:Holiday}){const min=sessions.reduce((sum,s)=>sum+s.duration_minutes,0);return <aside className="rounded-xl bg-slate-50 p-5"><p className="text-xs font-bold uppercase text-blue-700">Dia selecionado</p><h3 className="mt-2 text-lg font-bold capitalize">{date.toLocaleDateString("pt-BR",{weekday:"long",day:"numeric",month:"long"})}</h3>{holiday&&<div className="mt-4 rounded-lg border border-orange-200 bg-orange-50 p-3 text-sm text-orange-800"><b>Feriado</b><br/>{holiday.name}</div>}<p className="mt-5 text-sm font-bold">Sessões · {min} minutos</p><div className="mt-3 space-y-2">{sessions.map(s=><div key={s.id} className="rounded-lg border border-slate-200 bg-white p-3"><b className="text-sm">{s.subject}</b><p className="mt-1 text-xs text-slate-500">{s.duration_minutes} min · {s.status==="completed"?"concluída":"em andamento"}</p></div>)}{!sessions.length&&<p className="text-sm text-slate-500">Nenhuma sessão registrada para este dia.</p>}</div></aside>}
function Week({sessions,selected,onSelect}:{sessions:Session[];selected:Date;onSelect:(d:Date)=>void}){const first=addDays(selected,-selected.getDay());return <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-7">{Array.from({length:7},(_,i)=>addDays(first,i)).map(d=><button onClick={()=>onSelect(d)} key={d.toISOString()} className={`min-h-36 rounded-xl border p-3 text-left ${equalDate(d,selected)?"border-blue-500 bg-blue-50":"border-slate-200"}`}><p className="text-xs font-bold uppercase text-slate-400">{d.toLocaleDateString("pt-BR",{weekday:"short"})}</p><p className="mt-1 font-bold">{d.getDate()}</p>{sessionsOnDate(sessions,d).map(s=><p key={s.id} className="mt-2 rounded bg-blue-100 p-1.5 text-xs font-bold text-blue-800">{s.subject}<br/>{s.duration_minutes} min</p>)}</button>)}</div>}
function sessionsOnDate(sessions:Session[],date:Date){return sessions.filter(s=>equalDate(new Date(s.started_at),date))}function List({sessions,onSelect}:{sessions:Session[];onSelect:(d:Date)=>void}){return <div className="mt-5 divide-y divide-slate-100">{sessions.map(s=><button onClick={()=>onSelect(new Date(s.started_at))} key={s.id} className="flex w-full items-center justify-between py-4 text-left hover:bg-slate-50"><span><b>{s.subject}</b><small className="mt-1 block text-slate-500">{new Date(s.started_at).toLocaleDateString("pt-BR",{dateStyle:"long"})}</small></span><b className="rounded-full bg-blue-50 px-3 py-1 text-sm text-blue-700">{s.duration_minutes} min</b></button>)}{!sessions.length&&<p className="py-10 text-center text-sm text-slate-500">Nenhuma sessão encontrada.</p>}</div>}function Stat({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p></div>}
